version: '3.0'
services:
  cron:
    build: 
      context: .
      dockerfile: cron/Dockerfile
      args:
        MINUTE: "*"
        HOUR: "*"
        DAY_OF_MONTH: "*"
        MONTH: "*"
        DAY_OF_WEEK: "*"
        COMMAND: "echo Hello world"
    restart: always
    image: dengue_cron
    container_name: dengue_cron
    volumes:
      - data:/root/data
    healthcheck:
      test: ["CMD", "test", "-d", "/root/data"]
      interval: 10s
      retries: 5
  web:
    build:
        context: .
        dockerfile: web/Dockerfile
    container_name: dengue_web
    restart: always
    image: dengue_web
    ports:
      - 8989:80
    volumes:
      - data:/root/data
    healthcheck:
      test: ["CMD", "test", "-d", "/root/data"]
      interval: 10s
      retries: 5
volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data
